### ISSUE TITLE
Error 500 when trying to preview

### ISSUE THREAD

**Issue by tony-cp** [intellitrend/zabbix-csv-host-import-module#11]
I am running Zabbix 6.4.11. This is the error message I get when I try to preview after selecting file:

[Thu Feb 08 19:34:51.011211 2024] [php:error] [pid 299461] [client xx.xx.xx.xx:57896] PHP Fatal error:  Uncaught Error: Call to a member function name() on array in /usr/share/zabbix/modules/csv-host-importer/actions/CsvHostImport.php:158\nStack trace:\n#0 /usr/share/zabbix/modules/csv-host-importer/actions/CsvHostImport.php(397): Modules\\Ichi\\Actions\\CsvHostImport->csvParse()\n#1 /usr/share/zabbix/include/classes/mvc/CController.php(476): Modules\\Ichi\\Actions\\CsvHostImport->doAction()\n#2 /usr/share/zabbix/include/classes/core/ZBase.php(634): CController->run()\n#3 /usr/share/zabbix/include/classes/core/ZBase.php(233): ZBase->processRequest()\n#4 /usr/share/zabbix/include/config.inc.php(25): ZBase->run()\n#5 /usr/share/zabbix/zabbix.php(22): require_once('...')\n#6 {main}\n  thrown in /usr/share/zabbix/modules/csv-host-importer/actions/CsvHostImport.php on line 158, referer: https://azw1-zabbix.cp.local/zabbix/zabbix.php?action=ichi.import

**Comment by intellitrend-team** [comment]
Thank you for your issue. We have found the cause of the problem and have fixed it. The fix will be included with the next release.
