### ISSUE TITLE
[Feature] Add Macro Fields

### ISSUE THREAD

**Issue by jrf115** [intellitrend/zabbix-csv-host-import-module#15]
Would it be possible to add Hosts with multiple/different Macro values? 

Ex: 
Host1, {$Macro1}="Value1", {$Macro2}="Value2";
Host2, {$Macro1}="Value1", {$Macro2}="Value3";

**Comment by intellitrend-team** [comment]
Hello! First of all, sorry for the late response.

It should be easily possible to add support for macros, as it mostly follows the syntax of tags. We might be able to add it before the next release.
