### ISSUE TITLE
Host Import is failing!!

### ISSUE THREAD

**Issue by parul010282** [intellitrend/zabbix-csv-host-import-module#2]
Hi

We are trying to Import a bunch of Hosts using this Import Module. We have used the same example as stated in the documentation provided in this guide, however everytime we try to Import the host we face the below Error.

Invalid parameter "/output/1": value must be one of "groupid", "name", "flags", "uuid".
![image](https://user-images.githubusercontent.com/84312606/187424106-9e93aa3c-3a5a-42ea-9853-d3138fc5eaeb.png)

**Comment by intellitrend-team** [comment]
Thank you for your report. What Zabbix version are you using right now? And what is the exact content of your CSV file?

**Comment by intellitrend-team** [comment]
We found an error in the API call that was previously ignored by the Zabbix frontend framework. Please try again with the latest  release 6.0.3.
