### ISSUE TITLE
Import multiple host is not adding with same Host Group

### ISSUE THREAD

**Issue by ehsanshaikh85** [intellitrend/zabbix-csv-host-import-module#3]
When we tried to add multiple hosts by using Host CSV Importer methods, It's not adding the same Host Group. It's give the error (The host group already exists). Cloud anyone suggests this.

![image](https://user-images.githubusercontent.com/112493721/187460116-086ad47c-025c-4de6-ac0e-0dfdce5088bb.png)

**Comment by parul010282** [comment]
Yes, We face the same problem in or environment, seems Zabbix doesn't allow us to do a bulk upload of new Hosts on existing Host Groups!!

**Comment by intellitrend-team** [comment]
Hello, thank you for your report. We suspect that this issue is related to #2, since the first error message is the same. Please also write what Zabbix version you're using.

**Comment by ehsanshaikh85** [comment]
I am using the Zabbix 6.2.0 version.

**Comment by intellitrend-team** [comment]
We found an error in the API call that was previously ignored by the Zabbix frontend framework. Please try again with the latest  release 6.0.3.

**Comment by ehsanshaikh85** [comment]
Hi, Please note the version of zabbix we are using is 6.2.0, this is the latest release of zabbix as of now.

![image](https://user-images.githubusercontent.com/112493721/192445654-54345b33-b36b-4687-b834-216b8b1ab3ca.png)

is there a way of overcomming the "Host group already exists" error

**Comment by intellitrend-team** [comment]
That should be no problem with that release, the host importer module release 6.0.3 works both with Zabbix 6.0 and 6.2. Have you tried that release yet? If so, does this problem still persist? Feel free to comment about your experiences with 6.0.3.

**Comment by parul010282** [comment]
However the issue has been resolved, looks like the module got upgraded though the  frontend console is showing the older version.
