### ISSUE TITLE
6.0.3 release has wrong 'version' value

### ISSUE THREAD

**Issue by FireHelmet** [intellitrend/zabbix-csv-host-import-module#5]
Dear Intellitrend team,

Firstly, many thanks for this module, it save time for importing my hosts :).

I remarked a wrong value in 'version' inside the manifest.json of 6.0.3.zip, it comes with 6.0.1.

![image](https://user-images.githubusercontent.com/17533298/220374251-7b735eb0-fe52-4fb8-860e-17d5942219b9.png)

**Comment by intellitrend-team** [comment]
Thank you for your report. This issue has been fixed recently in 433575c but the release tag was still pointing to the previous commit. It should now include this commit as well.
