### ISSUE TITLE
Request compatibility with Zabbix 6.4

### ISSUE THREAD

**Issue by FireHelmet** [intellitrend/zabbix-csv-host-import-module#7]
Hello @intellitrend-team 

Please, could you release your module for Zabbix 6.4 ?

Many thanks !

**Comment by intellitrend-team** [comment]
Hello @FireHelmet,

We are planning to migrate our frontend modules in the second half of April. There are several breaking changes in the frontend module API for 6.4, so it will take some time on our side.

**Comment by intellitrend-team** [comment]
The release got delayed a bit, but version 6.1.0 has been released and supports Zabbix 6.4 now. It is functionally identical to 6.0.3.

Due to the new module schema, this release won't work with older Zabbix versions, but 6.0.3 should continue to work for Zabbix 6.0 and 6.2
