### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by pieterjanhaan** [intellitrend/zabbix-csv-host-import-module#9]
I try to install the module but it doesn't find it.

I'm running zabbix 6.0 on debian 10

![image](https://github.com/intellitrend/zabbix-csv-host-import-module/assets/149939725/fe0dbbf6-2fea-479b-9fce-4e9a4717afb1)

![image](https://github.com/intellitrend/zabbix-csv-host-import-module/assets/149939725/da7cce52-1755-4c92-ae84-2d2a06224e90)

**Comment by intellitrend-team** [comment]
Hello, it's possible that you have installed the newer version of the module that is compatible with Zabbix 6.4 only. For Zabbix 6.0, the latest version is [6.0.3](https://github.com/intellitrend/zabbix-csv-host-import-module/releases/tag/6.0.3).

**Comment by pieterjanhaan** [comment]
Okay then I'll try to update Zabbix to 6.4

**Comment by pieterjanhaan** [comment]
The issue is fixed by updating
